### ISSUE TITLE
youth.js有一条cookies获取不到

### ISSUE THREAD

**Issue by hunter8605** [Sunert/Scripts#11]
④ 在阅读文章最下面有个惊喜红包，点击获取惊喜红包请求

这条请求的cookies获取不到了，不知道是不是重写过期了？

**Comment by kingsleyzhnlanf** [comment]
> ④ 在阅读文章最下面有个惊喜红包，点击获取惊喜红包请求
> 
> 这条请求的cookies获取不到了，不知道是不是重写过期了？

我也是哎，大佬后来解决了嘛

**Comment by kingsleyzhnlanf** [comment]
果然要往下翻很久，才看见哈哈
