### ISSUE TITLE
中青Git Secrets配置问题

### ISSUE THREAD

**Issue by JohnHa0** [Sunert/Scripts#33]
在secrets中按照说明，将 四个cookie 按照& 隔开，运行的时候报错啊
🔔中青看点, 开始!
/home/runner/work/JD_Action/JD_Action/youth.js:81
      CookieYouth = process.env.YOUTH_HEADER.split()
                                             ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/home/runner/work/JD_Action/JD_Action/youth.js:81:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Error: Process completed with exit code 1.

求助

**Comment by q345665092** [comment]
我连cookie是哪个都不知道  没找到啊...

**Comment by q345665092** [comment]
> 在secrets中按照说明，将 四个cookie 按照& 隔开，运行的时候报错啊
> 🔔中青看点, 开始!
> /home/runner/work/JD_Action/JD_Action/youth.js:81
> CookieYouth = process.env.YOUTH_HEADER.split()
> ^
> 
> TypeError: Cannot read property 'split' of undefined
> at Object. (/home/runner/work/JD_Action/JD_Action/youth.js:81:46)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47
> Error: Process completed with exit code 1.
> 
> 求助

老哥 cookie 是哪个啊 四个我一个没找到

**Comment by q345665092** [comment]
> 在secrets中按照说明，将 四个cookie 按照& 隔开，运行的时候报错啊
> 🔔中青看点, 开始!
> /home/runner/work/JD_Action/JD_Action/youth.js:81
> CookieYouth = process.env.YOUTH_HEADER.split()
> ^
> 
> TypeError: Cannot read property 'split' of undefined
> at Object. (/home/runner/work/JD_Action/JD_Action/youth.js:81:46)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47
> Error: Process completed with exit code 1.
> 
> 求助

老哥 四个cookie 怎么找啊 抓包一堆 不知道哪个是哪个

**Comment by xtmnm** [comment]
兄弟你的中青能用吗

**Comment by JohnHa0** [comment]
并不能
________________________________

**Comment by JohnHa0** [comment]
________________________________

**Comment by Sunert** [comment]
去看说明，YOUTH_HEADER用#号

**Comment by Maccrack** [comment]
兄弟想问一下你是用哪个软件抓的cookie
