### ISSUE TITLE
安卓的中青看点如何获取ck

### ISSUE THREAD

**Issue by Castle1984** [Sunert/Scripts#36]
youth.js中的方法是只有ios才能用吗？我从手机上抓取了几个pcap包，用wirshark并没能分析cookie值，求教，有什么好方法吗？

**Comment by landcruser** [comment]
> youth.js中的方法是只有ios才能用吗？我从手机上抓取了几个pcap包，用wirshark并没能分析cookie值，求教，有什么好方法吗？
解决了吗?同问
