### ISSUE TITLE
电视家的cookie 到底如何配置啊，？

### ISSUE THREAD

**Issue by wishcaiji** [Sunert/Scripts#47]
请问电视家 github action 的 Secrets 如何配置呢？
实验了无数格式都不正确

抓包出来的是这样的：

{"Accept": "*/*","Accept-Encoding": "gzip, deflate","Accept-Language": "zh-Hans;q=1","AppVerCode": "173","AppVerName": "1.7.8","Authorization": "TURjM01qazFaVFpqWVRWbU1qSTJaak5tTURGalpETTFOVEl5TkdJeE1ERT1TYwNzA3MzI3NzUxNzgzMzkwOXwyOGEyNjg4OGMyMzdkZDY5NDNkYzM1ZTgyMGUyMjQ0YmQzZTZiMGVh","Cache-Control": "no-cache","Connection": "close","Cookie": "beegosessionID=3d5e44c526f16856654af1ff6c515a1ed","Generation": "com.dianshijia.mobile.ios","Host": "api.gaoqingdianshi.com","MarketChannelName": "Iphone","User-Agent": "Dsj/Client1.2","appId": "19227f89ea1a166451593601eb8a1b4f","areaCode": "410000","cityCode": "410100","countryCode": "CN","erid": "82851","ethMac": "","gpsCityCode": "410100","hwBrand": "iPhone","hwMac": "","hwModel": "iPhone10,2","ispId": "","language": "zh_CN","routerMac": "fc8e5bcbde1e","ssid": "0a93d9a0-e148-4d90-b6d9-5c5b1e755d60","userid": "8fc3bbcc95c0b6fa8b752cd9d255645b","uuid": "f6d57b51b2d14222878fa3685c4df4e0f",}

请问如何配置

**Comment by Sunert** [comment]
直接复制boxjs内的内容

**Comment by wishcaiji** [comment]
我用的是&nbsp;thor抓包的，复制那些内容？
格式是怎么样的呢？
