### ISSUE TITLE
快手值,具体是哪个？测试了好几个都错误。

### ISSUE THREAD

**Issue by hz378904298** [Sunert/Scripts#48]
'KUAISHOUMV'的一个值，拷贝抓包的请求体到下面Value的文本框中？
有没有样图？打码下也行。抓包工具不同，显示的也有些不同。

**Comment by djj-maker** [comment]
搜索kpg有一串http://数字的就是

**Comment by TWOBUG31** [comment]
> 搜索kpg有一串[http://数字的就是](http://%E6%95%B0%E5%AD%97%E7%9A%84%E5%B0%B1%E6%98%AF)
填入之后会加金币吗，我添加了14个在ac里边显示也正常，但是app金币没有增加

**Comment by hz378904298** [comment]
我也是的 金币没有增加

**Comment by wangxufire** [comment]
> 我也是的 金币没有增加
请求体是哪一个。。

**Comment by zing618** [comment]
'KUAISHOUMV'的一个值   请给个图 吧 我都没有看到什么数字
