### ISSUE TITLE
中青看看赚抓到的链接不同

### ISSUE THREAD

**Issue by qhq** [Sunert/Scripts#54]
您好
我中青看看赚没抓到提示的链接
有类似的是 https://ios.baertt.com/v5/Nameless/adlickstart.json和https://ios.baertt.com/v5/Nameless/adlickend.json

**Comment by Sunert** [comment]
现在只能做浏览赚的任务，下面的任务每个需要8个请求，太复杂，不打算添加了，你的那两个地址是下面的任务中的一部分，剩下6个就是做的阅读任务了
