### ISSUE TITLE
腾讯新闻AC的一些问题

### ISSUE THREAD

**Issue by wsr1005** [Sunert/Scripts#58]
关联了QQ账号登陆的，然后按下面的取到了
signurlVal:
密秘是从这开始写的（这个很多）：https://api.inews.qq.com/event/v1/user/event/report?mac=02000000******************
cookieVal:
密秘是从这开始写的：open_access_token=F2BA57CD29CC96818EAC88AE5FC2F5C7;v******************
videoVal:
密秘是从这开始写的：https://api.inews.qq.com/event/v1/user/event/r

但是有一个获取ID失败提示，不知道怎么处理。

AC还是出错了

==============📣系统通知📣==============
获取活动ID失败，详情请看日志
活动ID日志:{"data":{"activity":null,"activity_list":[{"id":"kuanian_zuji","h5":"https://gh.prize.qq.com/h5/plugin/2020zuji.html","show_type":"bottom_mini_bar","daily_show_times":0,"daily_close_times":1,"auto_close_seconds":0,"show_position":{"type":"channel","position":"KkVideo","channel_position":[{"tab_id":"news_news","type":"blacklist","channel_list":["news_news_19","news_news_game"]}],"index":0,"width":90,"height":108}}

**Comment by wsdjj** [comment]
老哥解决了吗，我也打算在云函数上跑，就是ck在脚本里找不到地方写入
