### ISSUE TITLE
聚看点脚本报错

### ISSUE THREAD

**Issue by 1217079729** [Sunert/Scripts#63]
![0C2F9A24-B28F-4256-B233-F1D517E177DE](https://user-images.githubusercontent.com/7964969/103432797-e8015d00-4c20-11eb-92f5-fc9130ae670d.png)

**Comment by monkey-sking** [comment]
你是怎么获得的cockie?我这里写了没有成功获取

**Comment by 1217079729** [comment]
> 你是怎么获得的cockie?我这里写了没有成功获取

我用的loon，脚本配置好打开app就获取到cookie了

**Comment by zyt821** [comment]
同样错误，是不是body的格式要改？

**Comment by nekomiao123** [comment]
我也是这个错误 怀疑就是body格式不太对劲

**Comment by 1217079729** [comment]
> 我也是这个错误 怀疑就是body格式不太对劲

相同的body 手机上跑就没问题

**Comment by monkey-sking** [comment]
求个获取cockie的配置

**Comment by nekomiao123** [comment]
求个格式，我ipad用quanx获取不到这个app的cookie和body，现在是自己抓包分析的（感觉不一定对）

**Comment by 1217079729** [comment]
> 求个格式，我ipad用quanx获取不到这个app的cookie和body，现在是自己抓包分析的（感觉不一定对）
![7735FC33-3E2D-41EF-B970-E79E59DD12E5](https://user-images.githubusercontent.com/7964969/103433755-e724f700-4c31-11eb-9b67-a849e338c613.png)

**Comment by nekomiao123** [comment]
找到解决办法了，就是抓取普通版聚看点的cookie就成了

**Comment by 1217079729** [comment]
> 找到解决办法了，就是抓取普通版聚看点的cookie就成了

多些，我试试看
