### ISSUE TITLE
baidu_speed.js在elecv2p环境下报错RefererUrl->undefined

### ISSUE THREAD

**Issue by kookpua** [Sunert/Scripts#88]
`
function confApi(api, body, RefererUrl) {
    return {
       url: 'https://haokan.baidu.com/activity/'+api,
       headers:{
           'Cookie': cookieval,
           'User-Agent': UA,
           'Referer': RefererUrl?RefererUrl:''
       },
       body:body
    }
}
`

我改成这样不报错了,想问下这样有什么后遗症吗?或者麻烦您在您的库中修复下 谢谢

` 'Referer': RefererUrl`
->
` 'Referer': RefererUrl?RefererUrl:''`

**Comment by Sunert** [comment]
好的
