### ISSUE TITLE
moji建议

### ISSUE THREAD

**Issue by DoveBoy** [Sunert/Scripts#92]
@Sunert 请求作者把moji.js完善一下，我想加入到云函数作为天气预报推送。能否利用现有的sendNotify.js加入Tg通知的推送？城市、每日天气、小时预报、生活指数、40天预告功能开关可否加入环境变量，方便调试以及云函数调用？

**Comment by Sunert** [comment]
NE环境已添加通知支持，至于关键变量，您直接在脚本中修改再上传吧
